In [1]:
import numpy as np
import torch
import copy
from torch import nn

In [2]:
torch.cuda.is_available()

/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 500: named symbol not found (Triggered internally at /opt/conda/conda-bld/pytorch_1695392067780/work/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0


False

In [7]:
t1 = torch.rand(5, 2)
t1.requires_grad_ = False

In [108]:
t2 = torch.rand(1, 5)
t2.requires_grad_()

tensor([[0.1826, 0.8183, 0.9520, 0.3222, 0.6825]], requires_grad=True)

In [23]:
t3 = torch.cat((t1, t2), 1).clone().detach()
t3.requires_grad_()

tensor([[0.1255, 0.8055, 0.7422],
        [0.8968, 0.0110, 0.4332],
        [0.5290, 0.9281, 0.2561],
        [0.6189, 0.1014, 0.3869],
        [0.9180, 0.2335, 0.1955]], requires_grad=True)

In [26]:
t4 = torch.rand(3, 6)

In [37]:
t5 = t3@t4
loss = t5.sum()

In [38]:
loss.backward()

In [39]:
t3.grad

tensor([[3.0188, 4.1511, 3.4013],
        [3.0188, 4.1511, 3.4013],
        [3.0188, 4.1511, 3.4013],
        [3.0188, 4.1511, 3.4013],
        [3.0188, 4.1511, 3.4013]])

In [93]:
midmat = torch.cat((t1, t2), 1)
t6 = midmat@t4
loss2 = t6.sum()
loss2.backward()

In [94]:
midmat

tensor([[0.1255, 0.8055, 0.7422],
        [0.8968, 0.0110, 0.4332],
        [0.5290, 0.9281, 0.2561],
        [0.6189, 0.1014, 0.3869],
        [0.9180, 0.2335, 0.1955]], grad_fn=<CatBackward0>)

In [46]:
t2.grad

tensor([[3.4013],
        [3.4013],
        [3.4013],
        [3.4013],
        [3.4013]])

In [52]:
torch.cat((a, b))

TypeError: expected Tensor as element 0 in argument 0, but got Linear

In [61]:
a = nn.Linear(5, 3)
a.weight

Parameter containing:
tensor([[-0.2589, -0.1072,  0.1219, -0.4166,  0.0140],
        [ 0.0392,  0.1890,  0.3297,  0.4130, -0.1619],
        [-0.3789, -0.0192, -0.3736, -0.2343,  0.4277]], requires_grad=True)

In [58]:
a.bias

Parameter containing:
tensor([ 0.0211,  0.3018, -0.0351], requires_grad=True)

In [64]:
c = torch.randn(1, 5)

In [78]:
a(c)

tensor([[ 0.0405, -0.1928,  0.6934]], grad_fn=<AddmmBackward0>)

In [69]:
c@t3

tensor([[ 1.5380, -0.7290,  0.3374]], grad_fn=<MmBackward0>)

In [82]:
a.weight

Parameter containing:
tensor([[-0.2589, -0.1072,  0.1219, -0.4166,  0.0140],
        [ 0.0392,  0.1890,  0.3297,  0.4130, -0.1619],
        [-0.3789, -0.0192, -0.3736, -0.2343,  0.4277]], requires_grad=True)

In [81]:
a.weight.size()

torch.Size([3, 5])

In [103]:
a = nn.Linear(5, 2)
a.requires_grad_(requires_grad=False)
b = nn.Linear(5, 3)
c = nn.Linear(5, 1)

In [110]:
a.bias

Parameter containing:
tensor([0.1184, 0.3810])

In [113]:
torch.cat((a.bias, c.bias))

tensor([ 0.1184,  0.3810, -0.3791], grad_fn=<CatBackward0>)

In [114]:
t2@torch.cat((a.weight, c.weight)).T + torch.cat((a.bias, c.bias))

tensor([[0.1665, 1.3676, 0.1326]], grad_fn=<AddBackward0>)

In [106]:
torch.cat((a.bias, c.bias))

tensor([ 0.1184,  0.3810, -0.3791], grad_fn=<CatBackward0>)

In [99]:
addweight = torch.ones(1, 5)
addweight.requires_grad_(requires_grad=False)
addbias = torch.ones(1)
addbias.requires_grad_(requires_grad=False)

tensor([1.])

In [100]:
a.weight = torch.cat((a.weight, addweight), 0)
a.weight

TypeError: cannot assign 'torch.FloatTensor' as parameter 'weight' (torch.nn.Parameter or None expected)